name = "nftysave-chainnft-dev"
account_id = "fffa4b4363a7e5250af8357087263b3a"
type = "webpack"
workers_dev = true
route = ""
zone_id = ""
vars = { DEBUG = true, TIME_BUDGET=60000, PAGE_SIZE=100, WORKER_POOL_SIZE = 1, LOCATION = "https://nftysave-chainnft-dev.protocol-labs.workers.dev/" }
kv_namespaces = [
  { binding = "EIP721_TOKENS", id = "ab00ecd632264dd99e8123f329c9d330", preview_id = "00c627aa820a480798ce0ce53da6018f" },
  { binding = "EIP721_CURSOR", id = "9339efcee8674aaa9e0da6870814897b", preview_id = "0858bca31e7440dea6bcb654214b172e" },
  { binding = "EIP721_SCAN", id = "5292a9c50a6844c794f52906f06ee8da", preview_id = "906afa11933748d0b1ff006342a99ad4" }
]

[triggers]
crons = ["* * * * *"]

[env.staging]
name = "nftysave-chainnft-staging"
vars = { DEBUG = true, TIME_BUDGET=60000, PAGE_SIZE=100, WORKER_POOL_SIZE = 1, LOCATION = "https://nftysave-chainnft-dev.protocol-labs.workers.dev/" }
kv_namespaces = [
  { binding = "EIP721_TOKENS", id = "6ac60cf8ac0f46868af62f5267bfbfea", preview_id = "d8f47f6802ec43edba4264191b2c71dc" },
  { binding = "EIP721_CURSOR", id = "1f5051378a3f46f49ad26b1823c58bea", preview_id = "90f20b9d3f9945d3bd3f847784ae6f2b" },
  { binding = "EIP721_SCAN", id = "04941ab39b194a3f9b3f480010a0fd9b", preview_id = "cec530f48d294338982a57d344918cdd" }
]
