name = "nftysave-chainnft-dev"
account_id = "fffa4b4363a7e5250af8357087263b3a"
type = "webpack"
workers_dev = true
route = ""
zone_id = ""
vars = { DEBUG = true, TIME_BUDGET=60000, PAGE_SIZE=100, WORKER_POOL_SIZE = 1, LOCATION = "https://nftysave-chainnft-dev.protocol-labs.workers.dev/" }
kv_namespaces = [ 
  { binding = "EIP721_TOKENS", id = "fcaab981736443c5b21957dfc0af5617", preview_id = "433cd69af9f8468d9dabe34bd2377187" },
  { binding = "EIP721_CURSOR", id = "1ed9f60450a848058b7c741996a43398", preview_id = "90f20b9d3f9945d3bd3f847784ae6f2b" },
  { binding = "EIP721_SCAN", id = "8bfdc339657d4c578043f7d7f2d1f909", preview_id = "e9ef5c66cee84858995d62f488a534dd" }
]

[triggers]
crons = ["* * * * *"]

[env.staging]
name = "nftysave-chainnft-staging"
vars = { DEBUG = true, TIME_BUDGET=60000, PAGE_SIZE=100, WORKER_POOL_SIZE = 1, LOCATION = "https://nftysave-chainnft-dev.protocol-labs.workers.dev/" }
kv_namespaces = [
  { binding = "EIP721_TOKENS", id = "6ac60cf8ac0f46868af62f5267bfbfea", preview_id = "d8f47f6802ec43edba4264191b2c71dc" },
  { binding = "EIP721_CURSOR", id = "1f5051378a3f46f49ad26b1823c58bea", preview_id = "90f20b9d3f9945d3bd3f847784ae6f2b" },
  { binding = "EIP721_SCAN", id = "04941ab39b194a3f9b3f480010a0fd9b", preview_id = "cec530f48d294338982a57d344918cdd" }
]
