on:
  # schedule:
  # - cron: */30 * * * *
  workflow_dispatch
name: ERC721

jobs:
  erc-7212:
    name: Scrape ERC-721
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ["staging", "production"]
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install dependencies
        run: yarn install

      - name: Run job
        env:
          DEBUG: "*"
          ENV: ${{ matrix.env }}
          FAUNA_KEY: ${{ secrets.FAUNA_KEY }}
          BATCH_SIZE: 100
          TIME_BUDGET: 1620
        run: yarn --cwd packages/scanner start
